config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :appointments

  resources :patients

  resources :anamnesis

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/anamnesi.rb
class Anamnesi < ActiveRecord::Base
  belongs_to :patient
end

app/controllers/anamnesis_controller.rb
class AnamnesisController < ApplicationController
  before_action :set_anamnesi, only: [:show, :edit, :update, :destroy]

  # GET /anamnesis
  # GET /anamnesis.json
  def index
    @anamnesis = Anamnesi.all
  end

  # GET /anamnesis/1
  # GET /anamnesis/1.json
  def show
  end

  # GET /anamnesis/new
  def new
    @anamnesi = Anamnesi.new
  end

  # GET /anamnesis/1/edit
  def edit
  end

  # POST /anamnesis
  # POST /anamnesis.json
  def create
    @anamnesi = Anamnesi.new(anamnesi_params)

    respond_to do |format|
      if @anamnesi.save
        format.html { redirect_to @anamnesi, notice: 'Anamnesi was successfully created.' }
        format.json { render :show, status: :created, location: @anamnesi }
      else
        format.html { render :new }
        format.json { render json: @anamnesi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anamnesis/1
  # PATCH/PUT /anamnesis/1.json
  def update
    respond_to do |format|
      if @anamnesi.update(anamnesi_params)
        format.html { redirect_to @anamnesi, notice: 'Anamnesi was successfully updated.' }
        format.json { render :show, status: :ok, location: @anamnesi }
      else
        format.html { render :edit }
        format.json { render json: @anamnesi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anamnesis/1
  # DELETE /anamnesis/1.json
  def destroy
    @anamnesi.destroy
    respond_to do |format|
      format.html { redirect_to anamnesis_url, notice: 'Anamnesi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anamnesi
      @anamnesi = Anamnesi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anamnesi_params
      params.require(:anamnesi).permit(:queixa_principal, :como_aconteceu, :data_inicio, :patient_id)
    end
end

app/helpers/anamnesis_helper.rb
module AnamnesisHelper
end

app/views/anamnesis/_form.html.erb
<%= form_for @anamnesi, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :queixa_principal, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :queixa_principal, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :como_aconteceu, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :como_aconteceu, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_inicio, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :data_inicio, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  anamnesis_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/anamnesis/edit.html.erb
<%- model_class = Anamnesi -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Anamnesi %></h1>
</div>
<%= render :partial => 'form' %>

app/views/anamnesis/index.html.erb
<%- model_class = Anamnesi -%>
<div class="page-header">
  <h1><%=t '.title', :default => Anamnesi %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:queixa_principal) %></th>
      <th><%= model_class.human_attribute_name(:como_aconteceu) %></th>
      <th><%= model_class.human_attribute_name(:data_inicio) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @anamnesis.each do |anamnesi| %>
      <tr>
        <td><%= anamnesi.id %></td>
        <td><%= anamnesi.queixa_principal %></td>
        <td><%= anamnesi.como_aconteceu %></td>
        <td><%= anamnesi.data_inicio %></td>
        <td><%=l anamnesi.created_at, format: :long %></td>
        <td>
          <%= link_to anamnesi_path(anamnesi), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to anamnesi_path(anamnesi), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_anamnesi_path,
            :class => 'btn btn-primary' %>

app/views/anamnesis/new.html.erb
<%- model_class = Anamnesi -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Anamnesi %></h1>
</div>
<%= render :partial => 'form' %>

app/views/anamnesis/show.html.erb
<%- model_class = Anamnesi -%>
<div class="page-header">
  <h1><%=t '.title', :default => Anamnesi %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:queixa_principal) %></dt>
      <dd><pre class="prettyprint"><%= @anamnesi.queixa_principal %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:como_aconteceu) %></dt>
      <dd><pre class="prettyprint"><%= @anamnesi.como_aconteceu %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:data_inicio) %></dt>
      <dd><pre class="prettyprint"><%= @anamnesi.data_inicio %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              anamnesis_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_anamnesi_path(@anamnesi), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              anamnesi_path(@anamnesi),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>