config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :appointments

  resources :patients

  resources :anamnesis

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  has_one :user
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:comentario, :data_entrada, :data_saida, :patient_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :comentario, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :comentario, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_entrada, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :data_entrada, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_saida, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :data_saida, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  appointments_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Appointment %></h1>
</div>
<%= render :partial => 'form' %>

app/views/appointments/index.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Appointment %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:comentario) %></th>
      <th><%= model_class.human_attribute_name(:data_entrada) %></th>
      <th><%= model_class.human_attribute_name(:data_saida) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.id %></td>
        <td><%= appointment.comentario %></td>
        <td><%= appointment.data_entrada %></td>
        <td><%= appointment.data_saida %></td>
        <td><%=l appointment.created_at, format: :long %></td>
        <td>
          <%= link_to appointment_path(appointment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to appointment_path(appointment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_appointment_path,
            :class => 'btn btn-primary' %>

app/views/appointments/new.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Appointment %></h1>
</div>
<%= render :partial => 'form' %>

app/views/appointments/show.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Appointment %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:comentario) %></dt>
      <dd><pre class="prettyprint"><%= @appointment.comentario %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:data_entrada) %></dt>
      <dd><pre class="prettyprint"><%= @appointment.data_entrada %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:data_saida) %></dt>
      <dd><pre class="prettyprint"><%= @appointment.data_saida %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              appointments_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_appointment_path(@appointment), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              appointment_path(@appointment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>